/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CaddyAppCard: typeof import('./components/appCard/caddyAppCard.vue')['default']
    ConfigShow: typeof import('./components/configShow.vue')['default']
    HttpServerCard: typeof import('./components/appCard/httpServerCard.vue')['default']
    PvButton: typeof import('primevue/button')['default']
    PvCard: typeof import('primevue/card')['default']
    PvDrawer: typeof import('primevue/drawer')['default']
    PvTag: typeof import('primevue/tag')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
